# app/config/security.yml

security:
    encoders:
        UserBundle\Entity\User:    sha512

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_PROFESSEUR, ROLE_ETUDIANT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            id:    fos_user.user_provider.username #le bundle inclut son propre fournisseur
            #entity:
                #class:    UserBundle\Entity\User
                #property:    username
        #in_memory:
            #memory:
                #users:
                    #prof:  { password: profpass, roles: [ 'ROLE_PROFESSEUR' ] }
                    #etudiant:  { password: etudiantpass, roles: [ 'ROLE_ETUDIANT' ] }
                    #admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    provider:    main
    #provider:    in_memory
    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:   ^/
            anonymous: true
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:    fos_user_security_logout
                target: /home
            remember_me:
                secret:     %secret% # %secret% est un paramètre de parameter

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN, requires_channel: https }