pgcp_default:
    path:     /
    defaults: { _controller: PGCPBundle:Home:index }


pgcp_homepage:
    path:     /home
    defaults: { _controller: PGCPBundle:Home:index }

pgcp_actualite:
    path:     /actualite/{id}
    defaults: { _controller: PGCPBundle:Home:actu }

#Etudiant ------------------------------------------------------------------
pgcp_etudiant:
    path:     /etudiant
    defaults: { _controller: PGCPBundle:Etudiant:index }

#---------------------------------------------------------------------------

#Chef de filiere-------------------------------------------------------------------

pgcp_chefdefiliere:
    path:     /chefdefiliere
    defaults: { _controller: PGCPBundle:ChefDeFiliere:index }

pgcp_chefdefiliere_valider:
    path:     /chefdefiliere/validerCours/{id}
    defaults: { _controller: PGCPBundle:ChefDeFiliere:validerCours }

#---------------------------------------------------------------------------

#Professeur------------------------------------------------------------------

pgcp_professeur:
    path:     /professeur
    defaults: { _controller: PGCPBundle:Professeur:index }

pgcp_professeur_ajouterCours:
    path:     /professeur/addCourse
    defaults: { _controller: PGCPBundle:Professeur:ajouterCours }

#---------------------------------------------------------------------------



#Administration-----------------------------------------
pgcp_admin:
    path:     /admin
    defaults: { _controller: PGCPBundle:Admin:index }



pgcp_admin_etudiant:
    path:     /admin/etudiant/{username}
    defaults: { _controller: PGCPBundle:Admin:etudiant }
pgcp_admin_professeur:
    path:     /admin/professeur/{username}
    defaults: { _controller: PGCPBundle:Admin:professeur }
pgcp_admin_admin:
    path:     /admin/admin/{username}
    defaults: { _controller: PGCPBundle:Admin:admin }
pgcp_admin_delete:
    path:     /admin/delete/{username}
    defaults: { _controller: PGCPBundle:Admin:delete }
pgcp_admin_chefdefiliere:
    path:     /admin/chefDeFiliere/{username}
    defaults: { _controller: PGCPBundle:Admin:chefdefiliere }

#------------------------------------------------------

#Actualites-----------------------------------------

pgcp_admin_ajouter_actualite:
    path:     /admin/ajouterActualite
    defaults: { _controller: PGCPBundle:Admin:ajouterActualite }

#------------------------------------------------------
#Slides-----------------------------------------

pgcp_admin_ajouter_slide:
    path:     /admin/ajouterSlide
    defaults: { _controller: PGCPBundle:Admin:ajouterSlide }

#------------------------------------------------------
